apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-pod
    tier: db-tier
spec:
  containers:
    - name: redisapp-db
      image: redis
      ports:
        - containerPort: 6379