apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
    tier: result-tier
spec:
  type: LoadBalancer
  ports:
    - name: resulting-app
      image: dockersamples/examplevotingapp_result
  selector:
    tier: result-tier