apiVersion: v1
kind: Pod
metadata:
  name:
    app: result
  labels:
    tier: result-tier
spec:
  containers:
    - name: resultapp
      image: dockersamples/examplevotingapp_result
  ports:
    - containerPort: 80