apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
    tier: result-tier
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30009
      port: 80
      targetPort: 80
  selector:
    tier: result-tier