apiVersion: v1
kind: Pod
metadata:
  name:
    app: result
    tier: result-tier
spec:
  containers:
    - name: resultapp
      image: dockersamples/examplevotingapp_result
  ports:
    - containerPort: 80