apiVersion: v1
kind: Pod
metadata:
  name: votingapp
  labels:
    app: myapp
spec:
  containers:
    - name: voting
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80