apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: ourapp
spec:
  type: NodePort
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 80
  selector:
    app: myapp